apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  minReadySeconds: 10
  replicas: 5
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: mycontainer
          image: 307854153830.dkr.ecr.eu-central-1.amazonaws.com/myrepo:latest
          ports:
            - containerPort: 80
